name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies and prepare environment
      run: |
        sudo apt update && sudo apt install -y python3 python3-pip python3-venv
        python3 -m pip install --user pipx
        pipx install pdm || true
        export PATH="$HOME/.local/bin:$PATH"
        pdm --version

    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          set -e
          cd /root/dummy_projects/SSH_VM_TEMPLATE
          pdm install
          source .venv/bin/activate
          python src/test_pipeline.py
