name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies and prepare environment
      run: |
        # Ensure system is updated
        sudo apt update && sudo apt install -y python3 python3-pip python3-venv

        # Install pipx and ensure path is configured
        python3 -m pip install --user pipx
        python3 -m pipx ensurepath
        export PATH="$HOME/.local/bin:$PATH"

        # Install PDM if not already installed
        if ! command -v pdm &> /dev/null; then
          pipx install pdm
        fi

        # Confirm PDM is available
        pdm --version

    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          set -e  # Stop execution on error
          
          # Ensure PDM environment is clean and dependencies are installed
          cd /root/dummy_projects/SSH_VM_TEMPLATE
          if [ ! -f pyproject.toml ]; then
            echo "Error: pyproject.toml not found. Aborting."
            exit 1
          fi
          /root/.local/bin/pdm install

          # Activate the virtual environment
          source .venv/bin/activate

          # Run the health check script
          python /root/dummy_projects/SSH_VM_TEMPLATE/tests/vps_health.py
