# Credits to : https://github.com/charbelmhanna/automation_deployment_workflow_linode_server/blob/main/main.yml
name: Deploy

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:       
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /root/dummy_projects/SSH_VM_TEMPLATE
          git pull origin main
          git status
          pdm install
          source .venv/bin/activate
          python /root/dummy_projects/SSH_VM_TEMPLATE/tests/vps_health.py
