on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to checkout and pull from'
        required: true
        default: 'main'
      work_dir:
        description: 'Directory to change to before pulling'
        required: true
        default: '/path/to/workdir'

jobs:
  run_pull:
    name: Run Pull
    runs-on: ubuntu-latest
    
    steps:
    - name: Install SSH keys
      # Check this thread to understand why it's needed:
      # https://stackoverflow.com/a/70447517
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_IP }} > ~/.ssh/known_hosts
    - name: Connect and pull
      # Connect to the server and create a directory named 'test_ssh'
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }} "mkdir test_ssh"
    - name: Cleanup
      # Remove the SSH keys to clean up
      run: rm -rf ~/.ssh
